# Default initial positions for armr5's ros2_control fake system

initial_positions:
  R0_Yaw: 0.0
  R1_Pitch: 0.0
  R2_Pitch: 0.0
  R3_Yaw: 0.0
  R4_Pitch: 0.0
  ServoGear: 0.0
  LeftGripper: 0.0
  LeftPivotArm: 0.0
  PassifGear: 0.0
  RightGripper: 0.0
  RightPivotArm: 0.0