camera:
  - id: 1
    transform: 
      - [1.0,  0.0,  0.0,  0.132] 
      - [0.0, -1.0,  0.0, -0.019]    
      - [0.0,  0.0, -1.0,  1.035]  
      - [0.0,  0.0,  0.0,    1.0]    
  - id: 2
    transform: 
      - [-1.0,   0.0,    0.0,  0.129]  
      - [ 0.0, 0.643,  0.766, -0.425]        
      - [ 0.0, 0.766, -0.643,  0.891]   
      - [ 0.0,   0.0,    0.0,    1.0]          
